/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://gc2nu2rsnncm3gsgly5lgb6ir4.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "powersightrestapi",
            "endpoint": "https://860qfshj67.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        },
        {
            "name": "AdminQueries",
            "endpoint": "https://6eha5wx5pd.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        },
        {
            "name": "validateEMail",
            "endpoint": "https://l5sxdebnq3.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-1:1a42955b-5b4d-4846-a56f-bd96bee2702e",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_F0uiXhSAc",
    "aws_user_pools_web_client_id": "40l1bq7jp27er8h7sb1l34cl9s",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "powersighta118a3c3f62e4994aecfa01048f2d7d032334-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
